### ISSUE TITLE
Awkward Usability

### ISSUE THREAD

**Issue by Xeno-Hypster** [nxghtmvrx/guides#1]
Since this is an extension of Mayfrost's list, it might be better if these extensions were attached to a fork of the original list, rather than requiring the reader to bounce between the two lists and possibly have to make inferences about the placement of your items in regards to the larger list.

**Comment by nxghtmvrx** [comment]
You are right. I discussed it earlier about why I've chosen to do it this way: I don't know how it compares to the rest of list(for example shells) and have half-finished additional guides which probably won't make sense to include inside fork.

**Comment by Xeno-Hypster** [comment]
This is fair. The added requirement on the reader to make inferences won't be solved if your list doesn't meld with the original exactly anyway.

I'll close this, it was a minor suggestion and I'm glad you're filling the gap regardless!
